name: Build and test
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 11
          - os: ubuntu-latest
            java: 17
          - os: ubuntu-latest
            java: 21
          - os: ubuntu-latest
            java: 25
          - os: macos-latest
            java: 17
          - os: windows-latest
            java: 17
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # TODO: Temporary fix for Windows (July 2025). See error message:
    # error STL1000: Unexpected compiler version, expected Clang 19.0.0 or newer
    - name: Setup Clang 19 (Windows only)
      if: runner.os == 'Windows'
      uses: egor-tensin/setup-clang@v1
      with:
        version: 19
        platform: x64
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - name: Setup Mill (MacOS/Ubuntu)
      if: runner.os != 'Windows'
      run: ./mill version
    - name: Setup Mill (Windows)
      if: runner.os == 'Windows'
      run: |
        curl.exe -L https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/1.1.5/mill-dist-1.1.5-mill.bat -o mill.bat
        ./mill version
    - name: Build
      run: ./mill __.compile
    - name: Test
      run: ./mill __.test
